name = "charli3/oracle_integration"
version = "0.1.0"
compiler = "v1.0.29-alpha"
plutus = "v2"
license = "Apache-2.0"
description = "A library to interact with Charli3 price feeds"

[repository]
user = "charli3"
project = "oracle_integration"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.9.0"
source = "github"
